AllCops:
  Exclude:
    - 'bin/*'
    - 'spec/spec_helper.rb'
    - 'tests/*'

Style/SymbolArray:
  Enabled: false

Metrics/MethodLength:
  Max: 23

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
